### ISSUE TITLE
Give sidebar more contrast from background

### ISSUE THREAD

**Issue by MichaelCurrin** [MichaelCurrin/python-twitter-guide#8]
```css
.sidebar {
    background-color: #333;
}
```

Also update hamburger
